#!/usr/bin/env python

import socket
import os
import time


HOST = os.getenv("DB_HOST")
PORT = int(os.getenv("DB_PORT"))


with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    print(" :: Starting connection test...")
    while True:
        try:
            print(" :: Trying to connect...")
            s.connect((HOST, PORT))
            s.close()
            break
        except socket.error:
            time.sleep(1)
            print(" :: Connection faild!")
    print(" :: Connection succeed!")
